### ISSUE TITLE
Improve launch speed for FBA

### ISSUE THREAD

**Issue by willbelr** [tiduscrying/MiniUI-Extra-Extras#1]
#!/bin/sh

EMU_EXE=fbalpha
CORES_PATH=$(dirname "$0")

###############################

EMU_TAG=$(basename "$(dirname "$0")" .pak)
ROM="$1"
mkdir -p "$BIOS_PATH/$EMU_TAG"
mkdir -p "$SAVES_PATH/$EMU_TAG"
HOME="$USERDATA_PATH"
cd "$HOME"

if [ $(stat -c%s "$ROM") -gt 10000000 ] ; then
  needs-swap
fi

picoarch "$CORES_PATH/${EMU_EXE}_libretro.so" "$ROM" &> "$LOGS_PATH/$EMU_TAG.txt"

**Comment by tiduscrying** [comment]
I absolutely love this idea! Taking inspiration from another user's Pak for FBNeo, I also added a screen that will show up when a larger ROM is loaded letting the user know to wait a second for the ROM to load. 

Thank you very much for posting this!
