### ISSUE TITLE
Pico-8 Games Not Booting

### ISSUE THREAD

**Issue by dlsellers** [tiduscrying/MiniUI-Extra-Extras#10]
Hey, thanks for your work on this! I mainly wanted to use this to play Pico-8 games. I unzipped and added all the contents from your latest release, and added my .p8 files in the correct roms folder, but trying to boot them from MiniUI just goes to a black screen and right back to the menu. Do you know what I might be missing? Thanks!

Bonus issue: I'd love to use the SNES core you provided, but I'm not actually seeing it included in the latest release. Am I just blind?

**Comment by TechDevangelist** [comment]
AudioServer support was added into MiniUI recently, with this addition the fake08 build is trying to reopen the audio device and crashes. I just submitted a PR with a fresh binary that addresses it on my MiniUI test cards. Can't say this enough, all of the hard work was eggs on RGH Discord; I'm just gluing his work together then submitting a PR.

**Comment by dlsellers** [comment]
Thank you! That PR solved the issue for me.
