### ISSUE TITLE
Pico 8 issues

### ISSUE THREAD

**Issue by Ledarium** [tiduscrying/MiniUI-Extra-Extras#14]
After installing latest release (https://github.com/tiduscrying/MiniUI-Extra-Extras/releases/tag/05-23-22) pico8 didn't work at all as reported in https://github.com/tiduscrying/MiniUI-Extra-Extras/issues/10.

I've tried to install .PAK from current master commit https://github.com/tiduscrying/MiniUI-Extra-Extras/commit/f3bcf47dc4daf6d89f70726db60b840c1a4f9425 , and the image is rotated 180 degrees.

Everything else in the system works fine, image is in correct orientation. I'm running MiniUI-20220603-0, firmware is 20220419

**Comment by tiduscrying** [comment]
I need to get back to testing, but I believe Pico 8 was fixed recently and with a MiniUI nightly. I'll test and hopefully push some updates tsoon.

**Comment by clems71** [comment]
Just tested current main branch [f3bcf47](https://github.com/tiduscrying/MiniUI-Extra-Extras/commit/f3bcf47dc4daf6d89f70726db60b840c1a4f9425). 

It runs properly on my Miyoo Mini 2, except the fact that the display is flipped along the Y axis :)

**Comment by clems71** [comment]
Found where the issue comes from : you need to delete the previous `libSDL-1.2.so.0` file coming from the previous release `MiniUI-Extra-Extras_05-23-22`

**Comment by Ledarium** [comment]
Can confirm that removing `libSDL-1.2.so.0` works for me. The issue can be closed, but maybe should account for that in `launch.sh` and specify exact name of library in `LD_LIBRARY_PATH`

**Comment by tiduscrying** [comment]
Fixed with the latest release! Thanks for the input everyone and sorry about the delay in getting to this one.
