### ISSUE TITLE
Quake.pak & CPS2.pak missing from the zip file

### ISSUE THREAD

**Issue by McFly75** [tiduscrying/MiniUI-Extra-Extras#19]
I have downloaded 3rd Release - 05-23-22.
But it does not have Quake or CPS1 pak (in Emus)
Also the ROMS folders for Quake, CPS1 systems are missing.
And the CPS2 folder in ROMS are missing.

**Comment by GamingOtter** [comment]
Also, I couldn't figure out how to Use the Super Game Boy Pak, any advice?

**Comment by jeff93063** [comment]
Quake doesn't show up in any of the 3 releases, but it's in the documentation. Can you add it to the zip? Thanks

**Comment by tiduscrying** [comment]
Fixed with the latest release! Sorry about that one folks!
