### ISSUE TITLE
Quake config file location

### ISSUE THREAD

**Issue by jeff93063** [tiduscrying/MiniUI-Extra-Extras#20]
The [documentation](https://github.com/tiduscrying/MiniUI-Extra-Extras#quake) says to put config.jpg into "/Saves/QUAKE/Quake" but it actually needs to go in "/Saves/QUAKE/Quake (QUAKE)" or inputs don't work. Also the filename should be config.cfg, not config.jpg.

**Comment by tiduscrying** [comment]
Fixed the readme in the latest release! Sorry about that 🙇‍♂️
