### ISSUE TITLE
Request - Add Screen Effects to 'Aspect' screen size

### ISSUE THREAD

**Issue by yaboybangz** [tiduscrying/MiniUI-Extra-Extras#26]
Howdy folks,

Unsure if this is in the right spot, couldn't open an issue on the main miniui page.

It would be outstanding if there were a way to add screen effects (scaliness/LCD/DMG) to emulators when using the 'aspect' or 'full' screen size options please.

Thanks,

Ed

**Comment by tiduscrying** [comment]
Hey there, dig the suggestion but screen effects, shaders and other stuff is very much outside my scope. These add-on packs are meant to be very as-is and just snap into what MiniUI already offers, so features like that wouldn't quite be doable on my end. That's all stuff with Picoarch and MiniUI, which are upstream. 

That being said, the screen effects were made to look the best with specific aspect ratios as far as I am aware, so they might not look as good being stretched or scaled. Sorry about that!
