### ISSUE TITLE
Would it be possible to run doxbox_pure on miniUI?

### ISSUE THREAD

**Issue by sherjilozair** [tiduscrying/MiniUI-Extra-Extras#3]

**Comment by VonSparq** [comment]
Could you please add a DOSBox pak, even if it's not going to work great?
I only have a handful of simple 2D games I need it for, Dangerous Dave, Keen 1 and a few others, I don't want to have to use Onion only because of them.

**Comment by tiduscrying** [comment]
Unfortunately it looks like DosBox-Pure is a no-go. I can't get the core to boot up likely due to some memory constraints within Picoarch. Sorry about that one!
