### ISSUE TITLE
CPS2 core?

### ISSUE THREAD

**Issue by retrogamecorps** [tiduscrying/MiniUI-Extra-Extras#6]
Hiya, would you mind adding the CPS2 core if you get a chance?  I tried running them on FBA and there were some slowdowns, so I am hoping that core can help.  Thanks, and zero rush :)

**Comment by tiduscrying** [comment]
Hi Russ! Just tested out fbalpha_2012_CPS2 and it works great. Bit busy right now, but hopefully I can get it added and push an update this weekend! Thanks for the support and interest in the project!

**Comment by retrogamecorps** [comment]
Thank you kindly, and Pico-8 was the icing on the cake!  Well done!
